"""
This file generates a unique tracking pixel link that 
can be logged and used to determine which email was opened.

Each email we want to track will be sent with a new link that is 
generated by this script
"""

import uuid

"""
Function that Generates the unique reciever ID that is appended onto each 
tracking pixel link
"""
def generate_pixel_url(reciever_id):
    pixel_url = "http://52.8.13.194/pixel.png"
    return f'{pixel_url}?reciever_id={reciever_id}'


def main_gen():
    reciever_id = str(uuid.uuid4())
    return generate_pixel_url(reciever_id), reciever_id
