"""
This file generates a unique tracking pixel link that 
can be logged and used to determine which email was opened.

Each email we want to track will be sent with a new link that is 
generated by this script
"""

import uuid

def generate_pixel_url(reciever_id):
    pixel_url = "http://52.8.13.194"
    return f'{pixel_url}?reciever_id={reciever_id}'


reciever_id = str(uuid.uuid4)

pixel_with_id = generate_pixel_url(reciever_id)
